name: llmos
services:
  llmos:
    build: ./app
    volumes:
      - ./app:/app
    ports:
      - 8502:8502
    env_file:
      - .env
    depends_on:
      - db
  db:
    hostname: db
    image: ankane/pgvector
    container_name: os-db
    ports:
     - 5432:5532
    restart: always
    environment:
      - POSTGRES_USER=llm-os
      - POSTGRES_PASSWORD=llm-os
      - POSTGRES_DB=os-vector
    volumes:
     - ./postgres/vector_extension.sql:/docker-entrypoint-initdb.d/init.sql
  pgadmin:
    image: dpage/pgadmin4
    container_name: os-pgadmin
    depends_on:
        - db
    ports:
        - "5053:80"
    environment:
        PGADMIN_DEFAULT_EMAIL: contact@brainzcode.com
        PGADMIN_DEFAULT_PASSWORD: brainzcode
    restart: always
volumes:
  postgres_data:


